// Generated by CoffeeScript 1.6.3
var app, assets, config, express, routes, stylus;

express = require('express');

stylus = require('stylus');

assets = require('connect-assets');

app = express();

app.port = process.env.PORT || process.env.VMC_APP_PORT || 3000;

config = require("./config");

app.configure('production', 'development', 'testing', function() {
  return config.setEnvironment(app.settings.env);
});

app.use(assets());

app.use(express["static"](process.cwd() + '/public'));

app.set('view engine', 'jade');

app.use(express.bodyParser());

routes = require('./routes');

routes(app);

module.exports = app;
