// Generated by CoffeeScript 1.6.2
var app, assets, config, db_stuff, db_url, express, orm, routes, stylus;

express = require('express');

stylus = require('stylus');

assets = require('connect-assets');

orm = require('orm');

app = express();

app.port = process.env.PORT || process.env.VMC_APP_PORT || 3000;

config = require("./config");

app.configure('production', 'development', 'testing', function() {
  return config.setEnvironment(app.settings.env);
});

db_url = process.env.DATABASE_URL || ("postgres://" + config.DB_USER + ":" + config.DB_PASS + "@" + config.DB_HOST + ":" + config.DB_PORT + "/" + config.DB_NAME);

console.log("connecting to:", db_url);

db_stuff = orm.express(db_url, {
  define: function(db, models, next) {
    return models.shipPositions = db.define('shipPositions', {
      id: Number,
      vesselName: String
    });
  }
});

app.use(db_stuff);

app.use(assets());

app.use(express["static"](process.cwd() + '/public'));

app.set('view engine', 'jade');

app.use(express.bodyParser());

routes = require('./routes');

routes(app);

module.exports = app;
