// Generated by CoffeeScript 1.6.2
module.exports = {
  index: function(req, res) {
    return req.models.shipPositions.count(function(err, count) {
      return res.render('shipPositions', {
        number_of_ship_positions: count
      });
    });
  }
};
